<a href="https://colab.research.google.com/github/vineelnekkanti/Python-for-Data-Science/blob/my-work/4)_Python_NumPy_Array_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
print(arr[5]) #value at index 5
print(arr[1:5])
print(arr[:7])
print(arr[7:])

6
[2 3 4 5]
[1 2 3 4 5 6 7]
[ 8  9 10]


IF you slice an array and assign a value to that sliced array then it will impact the original array. NumPy tries to avoid complex memory management. if you still want your original array to be unaffcected use **array_name.copy()** to have a back up of the original array

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[:5]
slice_of_arr

array([1, 2, 3, 4, 5])

In [16]:
#Now I am assigning a value to the new slice
slice_of_arr[:]=100
print(slice_of_arr)
print(arr)
#If you see this output, I have assinged new value to slice but NumPy
 #automatically picked those values back to the original np array

[100 100 100 100 100]
[100 100 100 100 100   6   7   8   9  10]


In [19]:
copy_of_arr = arr.copy()
copy_of_arr
copy_of_arr[:5]=99
print(arr)
print(copy_of_arr) #using copy unaffected the arrays

[100 100 100 100 100   6   7   8   9  10]
[99 99 99 99 99  6  7  8  9 10]


Indexing a 2-D Array/Matrix

In [25]:
arr_2d=np.random.randint(1,100,size=(3,5))
arr_2d

array([[15, 99, 14, 55, 73],
       [86, 67, 43, 19, 33],
       [77, 28, 12,  6, 77]])

2 formats to grab elements from matrix: double bracket and single bracket format

In [28]:

arr_2d[0][0]  #[][] row and the column
arr_2d[2][1] #Double brakcet format
#OR
arr_2d[2,1] #single bracket


28

In [36]:
#complex indexing
arr_2d[:2,2:] #first :2 display the rows from index 2 and next 2: works column wise
#arr_2d[:2]

array([[14, 55, 73],
       [43, 19, 33]])

In [39]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
bool_arr = arr > 5 #gives bool values
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr] #returns the values that has TRUE as value

array([ 6,  7,  8,  9, 10])

In [44]:
#simply put
print(arr[arr >5])
print(arr[arr <3])

[ 6  7  8  9 10]
[1 2]


In [49]:
#example
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [47]:
arr_2d[1:3,2:4]

array([[12, 13],
       [22, 23]])