<a href="https://colab.research.google.com/github/vineelnekkanti/Python-for-Data-Science/blob/my-work/5)%20Python_NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr+arr #doubles the values

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
#using the scalar element
print(arr+100)
print(arr-100)
print(arr*arr) #array on array operation
print(arr/100) #array with scalar operation

[100 101 102 103 104 105 106 107 108 109 110]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
[  0   1   4   9  16  25  36  49  64  81 100]
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]


In [12]:
arr/arr

<ipython-input-12-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
arr**2
#or
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [15]:
np.max(arr) #or arr.max()

10

In [16]:
np.min(arr)

0

In [18]:
np.exp(arr) #exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
np.log(arr) #logarithamic

<ipython-input-17-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])