<a href="https://colab.research.google.com/github/vineelnekkanti/Python-for-Data-Science/blob/my-work/Python_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Numeric python/NumPy is a linr algebra library of python, the reason it is
most important for python and Data Science is that almost all of the libraries in the PyData ecosystmer rely on NumPy as one of their main building blocks

2) Numpy is also incredibly fast as it has bindings to C libraries

3) NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

4) Arrays are very frequently used in data science, where speed and resources are very important.

For more refer: https://www.w3schools.com/python/numpy/default.asp

In [4]:
import numpy as np

1) NumPy arrays are the main way we will use NumPy throughout the course
2) These arrays are of two types: Vectors and Matrices
3) Vectors are 1-D arrays and Matrices are 2-D

Note that Matrix can stil have only one row or one column

In [5]:
#NumPy Arrays
my_list = [1,2,3]
arr = np.array(my_list) #casts the normal lists into numpy arrays
arr

array([1, 2, 3])

In [6]:
my_bin=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_bin)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)  # This is like range function in python: range(0,10)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(3)
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
#linspace
np.linspace(0,5,10) #10 evenly spaces points from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.linspace(0,5,20) #20 evenly spaces points from 0 to 5

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [31]:
#Create an Identity Matrix using NumPy
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

creating arrays with "Random"

In [32]:
np.random.rand(5) #create an array with the given shape we pass its gonna populate random samples from uniform distribution over 0 to 1
# This is 1-Dimensional

array([0.93236407, 0.28160284, 0.0293144 , 0.93999975, 0.97041005])

In [33]:
np.random.rand(5,5) #This creates a 2-D matrix with radom numbers

array([[0.54337403, 0.13009881, 0.64736289, 0.50655391, 0.94847115],
       [0.73884298, 0.62120787, 0.57594854, 0.5579748 , 0.91594756],
       [0.91103073, 0.13704172, 0.27042682, 0.15543665, 0.09041465],
       [0.82179389, 0.75564167, 0.15578036, 0.21546756, 0.15395058],
       [0.25427534, 0.66756723, 0.68381215, 0.57356734, 0.98736157]])

If we want to return a sample or many smaples from the standard normal distribution or a Gaussian distribution, instaed of using rand, we can used "randn"



In [35]:
np.random.randn(2) #This gives numbers from standard normal distribution

array([ 0.55677268, -2.09260796])

In [36]:
np.random.randn(4,4)

array([[-0.1265256 ,  0.01307865,  0.31334301,  0.23754701],
       [ 0.02531308, -1.10260786, -1.29402818, -0.92800573],
       [ 0.24129794,  0.26862604, -0.05571159,  0.01813739],
       [ 1.49594615, -0.47141882,  1.0868795 , -0.9226181 ]])

Random Integer

In [41]:
np.random.randint(1,100) # lowest inclusive and highest exlusive.
#It gives a random integer from: 1<=random integer<100

34

In [42]:
np.random.randint(1,100,10) #to display particularly 10 random integers from 1 till 99. It gives as an np array

array([57, 11,  6,  8, 87, 70, 85, 52, 20, 29])

In [65]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
rand_arr = np.random.randint(0,50,10)
rand_arr

array([30, 26, 45, 37,  3, 47, 15,  0, 27,  5])

you can use "reshape" function to reshape the dimensions of arrays

In [56]:
arr.reshape(4,5) #make sure if you multiply the numbers you should get the original number of elements in the old array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
rand_arr.reshape(5,2)

array([[30, 26],
       [45, 37],
       [ 3, 47],
       [15,  0],
       [27,  5]])

In [61]:
print(rand_arr.max())
print(rand_arr.min())


47
0


**argmax** and **argmin** helps in specifying the location of max and min values

In [63]:
print(rand_arr.argmax())
print(rand_arr.argmin())

5
7


In [68]:
arr.shape #shape helps in finding the shape of the vector

(20,)

In [76]:
arr=arr.reshape(5,4) #lets reshape the array
arr.shape

(5, 4)

In [79]:
arr.dtype # This helps in identiyfing the data type of the array

dtype('int64')

We can avoid coding long words like np.random.randint instead we can use in below format

In [81]:
from numpy.random import randint
randint(2,10,5)

array([9, 2, 6, 2, 4])